require("plugin/lualine_config")
require("plugin/toggleterm_config")
require("plugin/neo_tree_config")
require("plugin/nvim_treesitter_config")
require("plugin/coc_config")
-- require("plugin/lsp_config")
-- require("plugin/start_up_config")
require("plugin/start_up_default_config")
require("plugin/telescope_config")
require("plugin/auto_save_config")
